// Clause coverage: every blueprint clause and the test files that name it.
// Writes plan/MATRIX.md (generated; only the Lead runs this, at merge time).
// Usage: node tools/matrix.mjs [--summary]
import fs from 'node:fs'
import path from 'node:path'
import { ROOT } from './lib.mjs'

const PREFIXES = ['END', 'RULE', 'FLOW', 'EV', 'TB', 'RT', 'CK', 'AI', 'EX', 'RV', 'LL', 'SEC', 'ARC', 'LIVE', 'OUT']
const NOT_TESTED_BY_CODE = new Set(['RULE', 'OUT', 'LIVE'])
const ID = new RegExp(`\\b((?:${PREFIXES.join('|')})-\\d+)\\b`, 'g')

const clauses = new Map() // id -> blueprint file
const bpDir = path.join(ROOT, 'blueprint')
for (const f of fs.readdirSync(bpDir).filter((f) => /^\d\d-.*\.md$/.test(f)).sort()) {
  for (const line of fs.readFileSync(path.join(bpDir, f), 'utf8').split('\n')) {
    const m = line.match(/^\s*-\s+\*\*([A-Z]{2,5}-\d+)\*\*/)
    if (m && !/\(removed in v/.test(line)) clauses.set(m[1], f)
  }
}

const covered = new Map() // id -> Set of test files
const unknown = new Set()
const SKIP = new Set(['node_modules', '.next', '.git', 'playwright-report', 'test-results'])
function walk(dir) {
  let entries = []
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true })
  } catch {
    return
  }
  for (const e of entries) {
    if (SKIP.has(e.name)) continue
    const p = path.join(dir, e.name)
    if (e.isDirectory()) walk(p)
    else if (/\.(test|spec)\.[cm]?[jt]sx?$/.test(e.name)) {
      const rel = path.relative(ROOT, p).split(path.sep).join('/')
      for (const m of fs.readFileSync(p, 'utf8').matchAll(ID)) {
        if (!clauses.has(m[1])) unknown.add(m[1])
        else (covered.get(m[1]) || covered.set(m[1], new Set()).get(m[1])).add(rel)
      }
    }
  }
}
for (const d of ['src', 'testworld', 'e2e', 'tools']) walk(path.join(ROOT, d))

const testable = [...clauses.keys()].filter((id) => !NOT_TESTED_BY_CODE.has(id.split('-')[0]))
const done = testable.filter((id) => covered.has(id))
const pct = testable.length ? Math.round((100 * done.length) / testable.length) : 0
const summary = `Clauses ${testable.length} testable, ${done.length} with tests (${pct}%)`
console.log(summary + (unknown.size ? ` | unknown IDs in tests: ${[...unknown].sort().join(' ')}` : ''))

if (!process.argv.includes('--summary')) {
  const out = [
    '# Clause matrix',
    '',
    'Generated by `node tools/matrix.mjs` at merge time. Do not edit by hand.',
    '',
    summary,
    '',
    '| Blueprint file | With tests | Clauses still without a test |',
    '|---|---|---|',
  ]
  const files = [...new Set(clauses.values())].sort()
  for (const f of files) {
    const ids = testable.filter((id) => clauses.get(id) === f)
    if (!ids.length) continue
    const missing = ids.filter((id) => !covered.has(id))
    out.push(`| ${f} | ${ids.length - missing.length}/${ids.length} | ${missing.join(' ') || 'none'} |`)
  }
  if (unknown.size) out.push('', `Unknown clause IDs named in tests: ${[...unknown].sort().join(' ')}`)
  fs.writeFileSync(path.join(ROOT, 'plan', 'MATRIX.md'), out.join('\n') + '\n')
}
