// Clause coverage: every blueprint clause and the test files that name it.
// Writes plan/MATRIX.md (generated; only the Lead runs this, at merge time).
// Usage: node tools/matrix.mjs [--summary] [--plan]
// --plan also checks the card list: cards citing unknown clauses, testable
// clauses no card cites, non-family carded cards with no card file or no
// acceptance checks, and unknown dependencies. Exit 1 if any.
import fs from 'node:fs'
import path from 'node:path'
import { ROOT } from './lib.mjs'

const PREFIXES = ['END', 'RULE', 'FLOW', 'EV', 'TB', 'RT', 'CK', 'AI', 'EX', 'RV', 'LL', 'SEC', 'ARC', 'LIVE', 'OUT']
const NOT_TESTED_BY_CODE = new Set(['RULE', 'OUT', 'LIVE'])
const ID = new RegExp(`\\b((?:${PREFIXES.join('|')})-\\d+)\\b`, 'g')

const clauses = new Map() // id -> blueprint file
const bpDir = path.join(ROOT, 'blueprint')
for (const f of fs.readdirSync(bpDir).filter((f) => /^\d\d-.*\.md$/.test(f)).sort()) {
  for (const line of fs.readFileSync(path.join(bpDir, f), 'utf8').split('\n')) {
    const m = line.match(/^\s*-\s+\*\*([A-Z]{2,5}-\d+)\*\*/)
    if (m && !/\(removed in v/.test(line)) clauses.set(m[1], f)
  }
}

const covered = new Map() // id -> Set of test files
const unknown = new Set()
const SKIP = new Set(['node_modules', '.next', '.git', 'playwright-report', 'test-results'])
function walk(dir) {
  let entries = []
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true })
  } catch {
    return
  }
  for (const e of entries) {
    if (SKIP.has(e.name)) continue
    const p = path.join(dir, e.name)
    if (e.isDirectory()) walk(p)
    else if (/\.(test|spec)\.[cm]?[jt]sx?$/.test(e.name)) {
      const rel = path.relative(ROOT, p).split(path.sep).join('/')
      for (const m of fs.readFileSync(p, 'utf8').matchAll(ID)) {
        if (!clauses.has(m[1])) unknown.add(m[1])
        else (covered.get(m[1]) || covered.set(m[1], new Set()).get(m[1])).add(rel)
      }
    }
  }
}
for (const d of ['src', 'testworld', 'e2e', 'tools']) walk(path.join(ROOT, d))

const testable = [...clauses.keys()].filter((id) => !NOT_TESTED_BY_CODE.has(id.split('-')[0]))
const done = testable.filter((id) => covered.has(id))
const pct = testable.length ? Math.round((100 * done.length) / testable.length) : 0
const summary = `Clauses ${testable.length} testable, ${done.length} with tests (${pct}%)`
console.log(summary + (unknown.size ? ` | unknown IDs in tests: ${[...unknown].sort().join(' ')}` : ''))

if (!process.argv.includes('--summary')) {
  const out = [
    '# Clause matrix',
    '',
    'Generated by `node tools/matrix.mjs` at merge time. Do not edit by hand.',
    '',
    summary,
    '',
    '| Blueprint file | With tests | Clauses still without a test |',
    '|---|---|---|',
  ]
  const files = [...new Set(clauses.values())].sort()
  for (const f of files) {
    const ids = testable.filter((id) => clauses.get(id) === f)
    if (!ids.length) continue
    const missing = ids.filter((id) => !covered.has(id))
    out.push(`| ${f} | ${ids.length - missing.length}/${ids.length} | ${missing.join(' ') || 'none'} |`)
  }
  if (unknown.size) out.push('', `Unknown clause IDs named in tests: ${[...unknown].sort().join(' ')}`)
  fs.writeFileSync(path.join(ROOT, 'plan', 'MATRIX.md'), out.join('\n') + '\n')
}

if (process.argv.includes('--plan')) {
  const { cards } = JSON.parse(fs.readFileSync(path.join(ROOT, 'plan', 'slices.json'), 'utf8'))
  const ids = new Set(cards.map((c) => c.id))
  const problems = []
  const cited = new Set(cards.flatMap((c) => c.clauses || []))
  for (const c of cards) {
    for (const k of c.clauses || []) if (!clauses.has(k)) problems.push(`${c.id} cites unknown clause ${k}`)
    for (const d of c.deps || []) if (!ids.has(d)) problems.push(`${c.id} depends on unknown card ${d}`)
    if (c.status === 'carded' && !c.family) {
      const f = path.join(ROOT, 'plan', 'cards', `${c.id}.md`)
      if (!fs.existsSync(f)) problems.push(`${c.id} is carded but has no card file`)
      else if (!/## Acceptance checks/.test(fs.readFileSync(f, 'utf8'))) problems.push(`${c.id} card has no acceptance checks`)
    }
    if (c.family && !fs.existsSync(path.join(ROOT, 'plan', 'cards', 'families', `${c.family}.md`))) problems.push(`${c.id} family ${c.family} has no template`)
  }
  for (const id of testable) if (!cited.has(id)) problems.push(`clause ${id} is cited by no card`)
  const nl = String.fromCharCode(10) + '  '
  console.log(problems.length ? `PLAN: ${problems.length} problem(s)` + nl + problems.slice(0, 30).join(nl) : 'PLAN OK: every testable clause has a card, every card cites known clauses')
  if (problems.length) process.exitCode = 1
}
