-- Planted (SC R44): an identity seq a caller may set with OVERRIDING SYSTEM VALUE, and a version_no with no guard.
create schema if not exists returns;
create table returns.planted_state_events (
  id text primary key,
  seq bigint generated by default as identity
);
create table returns.planted_versions (
  id text primary key,
  version_no integer not null
);
